import { useEffect, useState, useRef } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowRight, BriefcaseBusiness, MapPin, Search, Sparkles, Upload, TrendingUp, FileText } from "lucide-react";
import Navbar from "../components/Navbar.jsx";
import JobCard from "../components/JobCard.jsx";
import { jobsApi } from "../services/api.js";
import { useAuth } from "../context/AuthContext.jsx";

const stats = [
  { label: "LIVE JOBS", value: "12.4k" },
  { label: "ACTIVE HIRING", value: "850+" },
  { label: "PROFILES SYNCED", value: "2.1M" },
  { label: "MATCH ACCURACY", value: "98%" }
];

const steps = [
  {
    title: "Upload Resume",
    description: "Our AI analyzes your career history, extracting latent skills and achievements often missed by human recruiters.",
    icon: FileText
  },
  {
    title: "Get Recommendations",
    description: "We match your cognitive map against thousands of elite job descriptions to find perfect cultural and technical fits.",
    icon: TrendingUp
  },
  {
    title: "Apply Jobs",
    description: "One-click application to vetted roles with personalized cover letters generated by our advanced AI writing engine.",
    icon: BriefcaseBusiness
  }
];

const JOB_SUGGESTIONS = [
  "MERN Stack Developer", "MEAN Stack Developer", "Python Developer", 
  "Mobile App Developer", "PHP Developer", "Product Manager",
  "Frontend Developer", "Full Stack Developer", "Flutter Developer",
  "Backend Developer", "Business Analyst", "React Developer", 
  "Ruby on Rails Developer", "UI/UX Designer", "Data Scientist", 
  "DevOps Engineer", "Software Engineer", "Machine Learning Engineer","Golang Developer"
];

const LOCATION_SUGGESTIONS = [
  "Bangalore, Karnataka","Bengaluru", "Kochi, Kerala", "Trivandrum, Kerala",
  "Kozhikode, Kerala", "Mumbai, Maharashtra", "Pune, Maharashtra",
  "Chennai, Tamil Nadu", "Hyderabad, Telangana", "Delhi NCR",
  "Remote", "Dubai, UAE"
];

function Home() {
  const navigate = useNavigate();
  const { user } = useAuth();
  const [featuredJobs, setFeaturedJobs] = useState([]);

  const [jobTitle, setJobTitle] = useState("");
  const [location, setLocation] = useState("");
  const [showJobSuggestions, setShowJobSuggestions] = useState(false);
  const [showLocSuggestions, setShowLocSuggestions] = useState(false);
  
  const jobRef = useRef(null);
  const locRef = useRef(null);

  useEffect(() => {
    if (user?.role === "recruiter") {
      navigate("/recruiter/manage");
    } else if (user?.role === "admin") {
      navigate("/admin");
    }
  }, [user, navigate]);

  useEffect(() => {
    jobsApi.list()
      .then(({ data }) => {
        const jobsList = data.jobs || data || [];
        setFeaturedJobs(Array.isArray(jobsList) ? jobsList.slice(0, 4) : []);
      })
      .catch(() => {
        setFeaturedJobs([]);
      });
  }, []);

  useEffect(() => {
    function handleClickOutside(event) {
      if (jobRef.current && !jobRef.current.contains(event.target)) setShowJobSuggestions(false);
      if (locRef.current && !locRef.current.contains(event.target)) setShowLocSuggestions(false);
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  const filteredJobs = JOB_SUGGESTIONS.filter(job => 
    job.toLowerCase().includes(jobTitle.toLowerCase())
  ).slice(0, 6); 

  const filteredLocs = LOCATION_SUGGESTIONS.filter(loc => 
    loc.toLowerCase().includes(location.toLowerCase())
  ).slice(0, 6);

  const handleSearch = (event) => {
    event.preventDefault();
    const params = new URLSearchParams();
    if (jobTitle) params.set("query", jobTitle);
    if (location) params.set("location", location);
    setShowJobSuggestions(false);
    setShowLocSuggestions(false);
    navigate(`/jobs?${params.toString()}`);
  };

  return (
    <div className="min-h-screen bg-white font-sans text-slate-900">
      <Navbar />

      <main>
        <section className="mx-auto max-w-7xl px-4 pt-12 sm:px-6 lg:px-8">
          <div className="grid items-center gap-12 lg:grid-cols-2">
            
            <div className="pr-8">
              <div className="inline-flex items-center gap-2 rounded-full bg-indigo-50 px-3 py-1.5 text-xs font-semibold tracking-wide text-indigo-600 uppercase">
                <Sparkles className="h-3.5 w-3.5" />
                AI-Powered Curation
              </div>
              
              <h1 className="mt-6 text-4xl font-bold tracking-tight text-indigo-950 sm:text-5xl lg:text-6xl leading-[1.1]">
                Find Your Dream<br />Job with AI
              </h1>
              
              <p className="mt-6 max-w-lg text-lg text-slate-500 leading-relaxed">
                The Cognitive Architect uses deep learning to map your skills to high-impact roles. Experience an editorial approach to career discovery.
              </p>

              <div className="mt-10 relative z-50">
                <form onSubmit={handleSearch} className="flex flex-col sm:flex-row w-full items-center overflow-visible rounded-xl border border-slate-200 bg-white p-1.5 shadow-sm focus-within:ring-2 focus-within:ring-indigo-600/20 focus-within:border-indigo-600 transition-all">
                  
                  <div className="flex w-full items-center gap-2 bg-white px-3 py-2 sm:w-2/5 relative" ref={jobRef}>
                    <Search className="h-5 w-5 text-slate-400 shrink-0" />
                    <input
                      type="text"
                      placeholder="Job title, keywords, or company"
                      className="w-full bg-transparent text-sm text-slate-900 outline-none placeholder:text-slate-400"
                      value={jobTitle}
                      onChange={(e) => {
                        setJobTitle(e.target.value);
                        setShowJobSuggestions(true);
                      }}
                      onFocus={() => setShowJobSuggestions(true)}
                    />
                    
                    {showJobSuggestions && jobTitle.trim().length > 0 && filteredJobs.length > 0 && (
                      <div className="absolute top-[120%] left-0 w-full min-w-[250px] bg-white rounded-lg shadow-xl border border-slate-100 py-2 z-[100] animate-in fade-in slide-in-from-top-2">
                        {filteredJobs.map((job, index) => (
                          <div 
                            key={index} 
                            className="px-4 py-2.5 hover:bg-indigo-50 cursor-pointer flex items-center gap-3 text-sm text-slate-700 transition-colors"
                            onClick={() => {
                              setJobTitle(job);
                              setShowJobSuggestions(false);
                            }}
                          >
                            <Search size={14} className="text-indigo-400 shrink-0" />
                            <span className="truncate">{job}</span>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>

                  <div className="hidden h-8 w-px bg-slate-200 sm:block"></div>

                  <div className="flex w-full items-center gap-2 bg-white px-3 py-2 sm:w-2/5 relative border-t border-slate-100 sm:border-t-0 mt-2 sm:mt-0" ref={locRef}>
                    <MapPin className="h-5 w-5 text-slate-400 shrink-0" />
                    <input
                      type="text"
                      placeholder="Location (e.g. Bengaluru, Kerala)"
                      className="w-full bg-transparent text-sm text-slate-900 outline-none placeholder:text-slate-400"
                      value={location}
                      onChange={(e) => {
                        setLocation(e.target.value);
                        setShowLocSuggestions(true);
                      }}
                      onFocus={() => setShowLocSuggestions(true)}
                    />

                    {showLocSuggestions && location.trim().length > 0 && filteredLocs.length > 0 && (
                      <div className="absolute top-[120%] left-0 w-full min-w-[250px] bg-white rounded-lg shadow-xl border border-slate-100 py-2 z-[100] animate-in fade-in slide-in-from-top-2">
                        {filteredLocs.map((loc, index) => (
                          <div 
                            key={index} 
                            className="px-4 py-2.5 hover:bg-indigo-50 cursor-pointer flex items-center gap-3 text-sm text-slate-700 transition-colors"
                            onClick={() => {
                              setLocation(loc);
                              setShowLocSuggestions(false);
                            }}
                          >
                            <MapPin size={14} className="text-indigo-400 shrink-0" />
                            <span className="truncate">{loc}</span>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>

                  <button type="submit" className="w-full sm:w-auto mt-3 sm:mt-0 rounded-lg bg-indigo-900 px-8 py-3 text-sm font-semibold text-white transition hover:bg-indigo-800 shrink-0">
                    Search Jobs
                  </button>

                </form>

                <div className="mt-5 flex items-center gap-2 text-sm text-slate-600">
                  <span>Or advance your profile:</span>
                  <Link to="/resume" className="inline-flex items-center gap-1.5 font-medium text-indigo-700 hover:text-indigo-800 transition-colors">
                    <Upload className="h-4 w-4" />
                    Upload Resume
                  </Link>
                </div>
              </div>
            </div>

            <div className="relative hidden lg:block z-0">
              <div className="relative h-[500px] w-full overflow-hidden rounded-[2.5rem] bg-slate-100">
                <img 
                  src="https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80" 
                  alt="Modern office space" 
                  className="h-full w-full object-cover"
                />
              </div>
            </div>

          </div>
        </section>

        <section className="mx-auto mt-20 max-w-7xl px-4 sm:px-6 lg:px-8 border-b border-slate-200 pb-16">
          <div className="grid grid-cols-2 gap-8 md:grid-cols-4 divide-x divide-slate-100">
            {stats.map((item) => (
              <div key={item.label} className="flex flex-col px-4 text-center sm:text-left">
                <p className="text-4xl font-bold text-indigo-950">{item.value}</p>
                <p className="mt-2 text-xs font-semibold uppercase tracking-widest text-slate-500">{item.label}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="mx-auto mt-20 max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
            <div>
              <h2 className="text-3xl font-bold text-indigo-950">Featured Opportunities</h2>
              <p className="mt-3 text-sm text-slate-500 max-w-md">
                Hand-picked by our neural network based on market authority and growth potential.
              </p>
            </div>
            <Link to="/jobs" className="inline-flex items-center gap-2 text-sm font-semibold text-indigo-700 hover:text-indigo-800 transition-colors">
              Explore all roles
              <ArrowRight className="h-4 w-4" />
            </Link>
          </div>
          
          <div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {featuredJobs.length ? featuredJobs.map((job) => (
              <JobCard key={job._id} job={job} compact />
            )) : (
              <p className="text-sm text-slate-500 col-span-full">No featured jobs available right now.</p>
            )}
          </div>
        </section>

        <section className="mt-24 bg-slate-50 py-24">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div className="text-center">
              <h2 className="text-3xl font-bold text-indigo-950">How It Works</h2>
              <p className="mx-auto mt-4 max-w-xl text-sm text-slate-500">
                Our three-step proprietary process ensures you find the path that matches your cognitive profile.
              </p>
            </div>

            <div className="mt-16 grid gap-10 lg:grid-cols-3">
              {steps.map((step) => {
                const Icon = step.icon;
                return (
                  <article key={step.title} className="text-center">
                    <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-white shadow-sm border border-slate-100 text-indigo-700">
                      <Icon className="h-7 w-7" />
                    </div>
                    <h3 className="mt-6 text-xl font-bold text-indigo-950">{step.title}</h3>
                    <p className="mx-auto mt-3 max-w-sm text-sm leading-relaxed text-slate-500">{step.description}</p>
                  </article>
                );
              })}
            </div>
          </div>
        </section>

        <section className="bg-indigo-950 py-20 text-center">
          <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
            <h2 className="text-3xl font-bold text-white sm:text-4xl">Ready to Architect Your Career?</h2>
            <p className="mt-4 text-indigo-200">
              Join thousands of professionals who have discovered their true potential.
            </p>
          </div>
        </section>
      </main>
    </div>
  );
}

export default Home;